name: uCarsTrade
main: net.stormdev.ucars.trade.main
version: 3
softdepend: [Vault]
depend: [uCars]
commands:
   ucarsTrade:
        description: This is the admin commands
        aliases: [car, ut, carsTrade, carTrade]
        usage: /<command> [Give Random] [Give <Speed> <Health> <Name>]
        permission: ucarstrade.admin
        permission-message: You don't have access to this command
        default: op